config/routes.rb
Trial2::Application.routes.draw do
  

  devise_for :users

  root "companies#index"

  resources :companies do
    resources :contacts do
      resource :notes
    end
  end
  
  resources :contacts do
    resources :notes
  end

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :contacts
  validates_presence_of :company_name
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company
  has_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :contact
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  # def require_user
    # if session[:user_id].nil?
      # redirect_to => new_user_session_url
    # else
      # @current_user = User.find(session[:user_id])
    # end
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @contacts = @company.contacts
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }        
      else
        @msg = ''
        @company.errors.full_messages.each do |m|
          @msg += m
        end
        flash[:notice]  = @msg
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :tags, :assigned_to, :email, :phone, :mobile_phone, :fax, :address1, :address2, :city, :state, :zip, :comments, :support_package)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @contacts = @company.contacts
    else
      @contacts = Contact.all
    end
      
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    if params[:company_id]
      @company = Company.find(params[:company_id])
      
    else
      @contacts = Contact.all
      
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :title, :tags, :assigned_to, :email, :phone, :mobile_phone, :fax, :address1, :address2, :city, :state, :zip, :comments, :support_package, :company_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @contact = Contact.find(params[:contact_id])
    @notes = Note.find(params[:contact_id])
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @contact = Contact.find(params[:contact_id])
    @notes = Note.find(params[:contact_id])
  end

  # GET /notes/new
  def new
    @note = Note.new
    @contact = Contact.find(params[:contact_id])
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @contact = Contact.find(params[:contact_id])
    
    respond_to do |format|
      if @note.save
        format.html { redirect_to @contact, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:note, :contact_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  
  
 <div class = 'row'>
	<div class = 'span3'>
		<%= f.input :company_name %>
	</div>
	<div class = 'span3'>
		<%= f.input :tags %>
	</div>
	<div class = 'span3'>
		<%= f.input :assigned_to %>
	</div>
	<div class = 'span3'>
		<%= f.input :email %>
	</div>
</div>

<div class = 'row'>
	<div class = 'span3'>
		<%= f.input :phone %>
	</div>
	<div class = 'span3'>
		<%= f.input :mobile_phone %>
	</div>
	<div class = 'span3'>
		<%= f.input :fax %>
	</div>
	<div class = 'span3'>
		<%= f.input :address1 %>
	</div>	
</div>
<div class = 'row'>
	<div class = 'span3'>
		<%= f.input :address2 %>
	</div>
	<div class = 'span3'>
		<%= f.input :city %>
	</div>
	<div class = 'span3'>
		<%= f.input :state %>
	</div>
	<div class = 'span3'>
		<%= f.input :zip %>
	</div>
</div>

<div class = 'row'>
	<div class = 'span3'>
		<%= f.input :support_package %>
	</div>
	
	<div class = 'span6'>
		<%= f.input :comments, :as => :text, :input_html => { :rows => 7 , :style => 'width: 90%'} %>
	</div>
</div>

<%= f.button :submit, :class => 'btn btn-primary' %>
<%end%>

<script>
	$(document).ready(function(){
		$("#company_phone").keydown(function(e){
		if (e.keyCode != 46 && e.keyCode != 8){
		    var company_val = $('#company_phone').val()
		    if(company_val.length==3){
		    $('#company_phone').val(company_val + '-')
		    }
		    if(company_val.length==7){
		    $('#company_phone').val(company_val + '-')
		    }}

		
		})
		
			$('input[name = commit]').click(function(){
			var msg = '';
			var company_name = $('#company_company_name').val();
			if( company_name == null || company_name == '' || company_name == undefined)
			{
			    msg += 'Company name required\n';
			    
			}
			var company_phone = $('#company_phone').val();
			
			if( company_phone == null || company_phone == '' || company_phone == undefined)
			{
			    msg += 'Company phone required';
			    
			}
			if(msg.length > 0){
			    alert(msg);
			    return false;
			}
			
			
			})
					
		})
	
	
</script>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to '<<Back', @company %>

app/views/companies/index.html.erb
<h1>List of Companies</h1>

<div class='row'>
	
	<div class = 'span2'>
		<b>Company name</b>
	</div>
	
	<div class = 'span2'>
		<b>Email</b>
	</div>
	
	<div class = 'span2'>
		<b>Phone</b>
	</div>
	
	<div class = 'span4'>
		
	</div>
	
</div>
</br>
<% @companies.each do |company| %>
<div class='row'>
	
	<div class = 'span2'>
		<uline><%= link_to company.company_name, company_path(company) %></uline>
	</div>
	
	<div class = 'span2'>
		<%= company.email %>
	</div>
	
	<div class = 'span2'>
		 <%= company.phone %>
	</div>
	
	<div class = 'span4'>
		<td><%= link_to 'Open', company, :class => 'btn btn-mini btn-primary'%></td> </br>
        </br>
	</div>
	
</div>
<%end%>

<br>

<%= link_to 'New Company', new_company_path, :class => 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path, :class => 'btn btn-primary' %>

app/views/companies/show.html.erb
<h1>Company Details</h1>

</br>

<div class = 'row'>
	<div class='span9'>
		<div class = 'row'>
			<div class = 'span2'>
				<strong>Company name:</strong></br>
		  		<%= @company.company_name %>
			</div>
			<div class = 'span2'>
				<strong>Tags:</strong></br>
		  		<%= @company.tags %>
			</div>
			<div class = 'span2'>
				<strong>Assigned to:</strong></br>
		  		<%= @company.assigned_to %>
			</div>
			<div class = 'span2'>
				<strong>Email:</strong></br>
		  		<%= @company.email %>
			</div>
		</div>
		
		</br>
		
		<div class = 'row'>
			<div class = 'span2'>
				<strong>Phone:</strong></br>
		  		<%= @company.phone %>
			</div>
			<div class = 'span2'>
				<strong>Mobile phone:</strong></br>
		  		<%= @company.mobile_phone %>
			</div>
			<div class = 'span2'>
				<strong>Fax:</strong></br>
		  		<%= @company.fax %>
			</div>
			<div class = 'span2'>
				<strong>Address1:</strong></br>
		  		<%= @company.address1 %>
			</div>
		</div>
		
		</br>
		
		<div class = 'row'>
			<div class = 'span2'>
				<strong>Address2:</strong></br>
		  		<%= @company.address2 %>
			</div>
			<div class = 'span2'>
				<strong>City:</strong></br>
		  		<%= @company.city %>
			</div>
			<div class = 'span2'>
				<strong>State:</strong></br>
		  		<%= @company.state %>
			</div>
			<div class = 'span2'>
				<strong>Zip:</strong></br>
		  		<%= @company.zip %>
			</div>
		</div>
		
		</br>
		
		<div class = 'row'>
			<div class = 'span2'>
				<strong>Support package:</strong></br>
		  		<%= @company.support_package %>
			</div>
			
			<div class = 'span6'>
				<strong>Comments:</strong></br>
		  		<%= @company.comments %>
			</div>
		</div>
	</div>
	
	<div class='span2 contacts'>
		<ul>
			<h4>Contacts</h4>
			<%@contacts.each do |contact|%>				
					<%fullName = contact.last_name + ", " + contact.first_name%>
					<li><%=link_to fullName, company_contact_path(@company, contact)%> </br></li>				
			<%end%>
		</ul>
	</div>

</div>

</br>
<style>
.row{
	zoom; 1;
	margin-left : -20px;
}

.row > [class*="contacts"]{
	display :inline;
	float :left;
	margin-leftt : 20px;

}

.span2.contacts{
	width : 220px;
	border : 1px solid #ccc;
	padding-left : 20px;

}


</style>


<%= link_to '<<Back', companies_path, :class => 'btn btn-mini btn-primary' %> | 
<%= link_to 'Edit', edit_company_path(@company), :class => 'btn btn-mini btn-primary' %> | 
<%= link_to 'Delete', company_path(@company), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-primary' %> |
<%=link_to 'Add a Contact', new_company_contact_path(@company), :class => 'btn btn-mini btn-primary'%>

app/views/contacts/_form_company_contact.html.erb
<%= simple_form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class='row'>
	<div class='span3'>
		<%= f.input :first_name %>
	</div>
	
	<div class='span3'>
		<%= f.input :last_name %>
	</div>
	
	<div class='span3'>
		<%= f.input :title %>
	</div>
		
	<div class='span3'>
		<%= f.input :tags %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :assigned_to %>
	</div>
	
	<div class='span3'>
		<%= f.input :email %>
	</div>
	
	<div class='span3'>
		<%= f.input :phone %>
	</div>
		
	<div class='span3'>
		<%= f.input :mobile_phone %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :fax %>
	</div>
	
	<div class='span3'>
		<%= f.input :address1 %>
	</div>
	
	<div class='span3'>
		<%= f.input :address2 %>
	</div>
		
	<div class='span3'>
		<%= f.input :city %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :state %>
	</div>
	
	<div class='span3'>
		<%= f.input :zip %>
	</div>
	
	<div class='span3'>
		<%= f.input :support_package %>
	</div>
		
	<div class='span3'>
		
	</div>
</div>

<div class='row'>
	<div class='span6'>
		<%= f.input :comments %>
	</div>
	
	<div class='span3'>
		<%=f.input :company_id, :as => :hidden, :input_html => { :value => params[:company_id] }%>
	</div>
	
</div>

    
<div class="actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/contacts/_form_contact.html.erb
<%= simple_form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class='row'>
	<div class='span3'>
		<%= f.input :first_name %>
	</div>
	
	<div class='span3'>
		<%= f.input :last_name %>
	</div>
	
	<div class='span3'>
		<%= f.input :title %>
	</div>
		
	<div class='span3'>
		<%= f.input :tags %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :assigned_to %>
	</div>
	
	<div class='span3'>
		<%= f.input :email %>
	</div>
	
	<div class='span3'>
		<%= f.input :phone %>
	</div>
		
	<div class='span3'>
		<%= f.input :mobile_phone %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :fax %>
	</div>
	
	<div class='span3'>
		<%= f.input :address1 %>
	</div>
	
	<div class='span3'>
		<%= f.input :address2 %>
	</div>
		
	<div class='span3'>
		<%= f.input :city %>
	</div>
</div>

<div class='row'>
	<div class='span3'>
		<%= f.input :state %>
	</div>
	
	<div class='span3'>
		<%= f.input :zip %>
	</div>
	
	<div class='span3'>
		<%= f.input :support_package %>
	</div>
		
	<div class='span3'>
		
	</div>
</div>

<div class='row'>
	<div class='span6'>
		<%= f.input :comments %>
	</div>
	
	<div class='span3'>
		<%= f.input :company_id %>
	</div>
	
</div>

    
<div class="actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/contacts/_note.html.erb
<h1><small>Notes</small></h1>

<%=note.note%>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact, :class => 'btn btn-mini btn-primary' %> |
<%= link_to 'Back', contacts_path, :class => 'btn btn-mini btn-primary' %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<div class='row'>
	
	<div class = 'span2'>
		<b>Last Name</b>
	</div>
	
	<div class = 'span2'>
		<b>First Name</b>
	</div>
	
	<div class = 'span2'>
		<b>Email</b>
	</div>
	
	<div class = 'span2'>
		<b>Phone</b>
	</div>
	
	<div class = 'span3'>
		
	</div>
	
</div>

</br>

<%@contacts.each do |contact|%>

<div class='row'>
	
	<div class = 'span2'>
		<td><%= link_to contact.last_name, contact_path(contact) %></td>
	</div>
	
	<div class = 'span2'>
		<td><%= contact.first_name %></td>
	</div>
	
	<div class = 'span2'>
		<td><%= contact.email %></td>
	</div>
	
	<div class = 'span2'>
		<td><%= contact.phone %></td>
	</div>
	
	<div class = 'span3'>
		
	</div>
	
</div>
</br>

<%end%>

<br>

<%if params[:company_id]%>
	<%= link_to 'New Contact', new_company_contact_path, :class => 'btn btn-mini btn-primary' %>
<%else%>
	<%= link_to 'New Contact', new_contact_path, :class => 'btn btn-mini btn-primary' %>
<%end%>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%if params[:company_id]%>
	<%= render 'form_company_contact' %>
<%else%>
	<%= render 'form_contact' %>
<%end%>

<%= link_to 'Back', contacts_path, :class => 'btn btn-mini btn-primary' %>

app/views/contacts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<div class='row'>
   
    <div class = 'span8'>
       
       <h1><small>Notes</small></h1>
       
     	<%@contact.notes.order('updated_at desc').each do |n|%>
     		<p><%=n.note%></br>
     		<small><%=n.updated_at.localtime%></small>
     			<%if not n.user_id.nil?%>
     				<small>| <%=User.find(n.user_id).email.split('@')[0]%></small>
     			<%end%>
     		</p>
     	<%end%>
     	
       	<%=link_to "Add a Note", new_contact_note_path(@contact)%>
       
    </div>
   
    <div class = 'span4 contact_info'>
       
        <strong><%= @contact.title + ". "+ @contact.first_name + ' ' + @contact.last_name %></strong> </br>
        <strong><small>Tags:</small></strong></br>
          <%= @contact.tags %></br>
         
          <strong><small>Assigned to:</small></strong></br>
          <%= @contact.assigned_to %></br>
   
        <strong><small>Email:</small></strong></br>
          <%= @contact.email %></br>
   
        <strong><small>Phone:</small></strong></br>
          <%= @contact.phone %></br>
   
        <strong><small>Mobile phone:</small></strong></br>
          <%= @contact.mobile_phone %></br>
         
          <strong><small>Fax:</small></strong></br>
          <%= @contact.fax %></br>
   
        <strong><small>Address:</small></strong></br>
          <%= @contact.address1 %></br>
          <%= @contact.address2 %></br>
        <%= @contact.city  + ", " + @contact.state + " " + @contact.zip%></br>
       
        <strong><small>Support package:</small></strong></br>
          <%= @contact.support_package %></br>
   
        <strong><small>Company:</small></strong></br>
          <%= @contact.company_id %></br>
         
          <strong><small>Comments:</small></strong></br>
          <%= @contact.comments %></br>
         
    </div>
   
    <style>
.row{
    zoom; 1;
    margin-left : -20px;
}

.row > [class*="contact_info"]{
    display :inline;
    float :left;
    margin-leftt : 20px;

}

.span4.contact_info{
    width : 220px;
    border : 1px solid #ccc;
    padding-left : 20px;

}


</style>
   
</div>
   

</br>

<%= link_to 'Edit', edit_contact_path(@contact), :class => 'btn btn-mini btn-primary' %> |
<%if params[:company_id]%>
	<%= link_to 'Back to Company Info', company_path(@company), :class => 'btn btn-mini btn-primary' %>
<%else%>
	<%= link_to 'Back to Contacts', contacts_path, :class => 'btn btn-mini btn-primary'%>
<%end%>

app/views/layouts/_header.html.erb
    <div class="navbar">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <a class="brand" href="#">DP CRM</a>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    
    <ul class="nav">
	    
	    <li><%=link_to 'Home', root_path%></li>
	    <li><%=link_to 'Companies', companies_path%></li>
	    <li><%=link_to 'Contacts', contacts_path%></li>
    </ul>
    
    <ul class="nav pull-right">
    	<%if user_signed_in?%>
        	<li><%= link_to 'Logout',  destroy_user_session_path, :method => "delete" %></li>
        <%else%>
        	<li><%= link_to 'Login',  user_session_path %></li>
        <%end%>
    </ul>
    
    </div>
     
    </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trial2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<div class = 'container'>
<body>
	<%=render '/layouts/header'%>
	<% unless flash.notice.nil? %>
		<div class="alert alert-info"><%=flash.notice%></div>
	<% end %>
<!-- <%flash.each do |name, msg|%>
	<%=content_tag(:div, msg, :class => 'alert alert-info')%>
<%end%> -->
<%= yield %>

</body>
</div>
</html>

app/views/notes/_form_contact_note.html.erb
<%= simple_form_for @note, :url => contact_notes_path(@contact, @note), :method => :post do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :note %>
    <!-- <%= f.association :contact, :collection => Contact.all.order("last_name"), :label_method => lambda {|r| "#{r.last_name},  #{r.first_name}"}, :input_html => { :value => params[:contact_id]}  %> -->
    <%= text_field_tag :contact_name, @contact.last_name + ", " + @contact.first_name, :readonly => true %>
    <%= f.input :contact_id, :as => 'hidden', :input_html => {:value =>@contact.id} %>
    <%= f.input :user_id, :as => 'hidden', :input_html => {:value =>current_user.id} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/notes/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Contact</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.note %></td>
        <td><%= note.contact %></td>
        <td><%= note.user %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Contact</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.note %></td>
        <td><%= note.contact %></td>
        <td><%= note.user %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_contact_note_path(@contact) %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form_contact_note' %>

<%= link_to 'Back', contact_path(@contact) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @note.contact %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>